### PR TITLE
[contrib] Autoresponder message hook

### PR DESCRIPTION
**Pull request by ikedas**
This is a simple autoresponder applicable to Sympa's mailing lists.

### CODE REVIEW

**Comment by racke** [comment]
Shouldn't that check the precedence of the incoming email, e.g. don't reply to "Precedence: bulk" messages?

**Comment by ikedas** [comment]
> Shouldn't that check the precedence of the incoming email, e.g. don't reply to "Precedence: bulk" messages?

No.  Currently this responds to anything that will be distributed to subscribers.  That is, it won't respond to rejected, held (for confirmation or moderation) or discarded messages.

**Comment by ikedas** [comment]
> > Shouldn't that check the precedence of the incoming email, e.g. don't reply to "Precedence: bulk" messages?
> 
> No. Currently this responds to anything that will be distributed to subscribers. That is, it won't respond to rejected, held (for confirmation or moderation) or discarded messages.

Done.  See 0beb49a

**Comment by racke** [comment]
Good :-). If you can please also add a license (statement), it should be ready to merged. Maybe we can flag it as "beta" somehow.

**Comment by ikedas** [comment]
I added copyright notice & license statement to the source file (*).

----
(*) I worried separate file like `LICENSE.md` might confuse GitHub's auto-detection of license for repository.

**Comment by racke** [comment]
OK, good. I'm fine with merging it now.

**Pull request merged**
