### PR TITLE
Add tip for Debian users in Readme

### PR DESCRIPTION
**Pull request by tvo6**

### CODE REVIEW

**Comment by racke** [comment]
@dverdin Please don't merge PRs with unnecessary merges like 3380072.

**Comment by dverdin** [comment]
Sorry. Git manipulation error.

**Comment by tvo6** [comment]
May you be more explicit on the problem? I think I did something wrong, but I'm not sure…

**Comment by racke** [comment]
@tvo6 Always create a branch on your fork for PRs :-)

**Comment by tvo6** [comment]
ok noted, thanks for the info!

**Pull request merged**
